### ISSUE TITLE
Stickers don't render correctly with the florian setting

### ISSUE THREAD

**Issue by mikebolt** [molarmanful/gCube#4]
When there is a nonzero florian size, the cube renders incorrectly. The problem is that there are some white areas in the corners of the stickers some of the time. You can see the problem in this picture:
![cube_florian](https://cloud.githubusercontent.com/assets/2136767/9020264/aa4f4488-37b6-11e5-821c-70c6ba821004.png)

I'm using Chrome v44.

**Comment by molarmanful** [comment]
Oh yeah, this is to be expected. It doesn't look too good though... I'll add you as contributor to this repo. You can help me!

**Comment by molarmanful** [comment]
Alright, fixed the issue.

**Comment by mikebolt** [comment]
This fixed it for me. See if you can pull the new css out of gcube.js and into a css file, although I think it would be best to find a way to create the appropriate css programmatically without all the repetition. You could do this by getting a list of all the center stickers, all the top-left corner stickers, all the bottom edge stickers, etc... and then just apply a single style to each of the lists.
