### ISSUE TITLE
Minified cuber code should not be included in gcube.js

### ISSUE THREAD

**Issue by mikebolt** [molarmanful/gCube#6]
This is my opinion of course, but I think that the minified cuber/Google cube code should not be included in gcube.js. It makes development annoying because my editor has a really long horizontal scroll bar at the bottom. It also means that if there are any changes to the underlying cuber project (which I actually anticipate), then the code has to be minified and pasted into gcube.js every time it changes.

I think it would be best if it were left out of gcube.js, but included in the minified gcube.js. This way development is easier and the users still have the option to include only a single script. It also makes it easier to break up gcube.js into multiple source files, should it start getting too big to manage.

**Comment by molarmanful** [comment]
Sure, I'm fine with anything. Never really thought of this, but sure!

**Comment by molarmanful** [comment]
Updated. In gcube.min.js, there is a comment indicating where to put the minified gcube.js so that you don't have to reminify google-cube-code.js.
